// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_compute_xiqr
int rcpp_compute_xiqr(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_compute_xiqr(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_xiqr(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_filter_threshold_xiqr
int rcpp_filter_threshold_xiqr(Rcpp::List& data, double thr);
RcppExport SEXP _ramr_rcpp_filter_threshold_xiqr(SEXP dataSEXP, SEXP thrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_filter_threshold_xiqr(data, thr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_filter_threshold_pval
int rcpp_filter_threshold_pval(Rcpp::List& data, double thr);
RcppExport SEXP _ramr_rcpp_filter_threshold_pval(SEXP dataSEXP, SEXP thrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_filter_threshold_pval(data, thr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_iqr
int rcpp_get_iqr(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_get_iqr(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_iqr(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_prepare_data
Rcpp::List rcpp_prepare_data(Rcpp::IntegerVector& seqnames, Rcpp::IntegerVector& seqrunlens, Rcpp::IntegerVector& start, Rcpp::IntegerVector& strand, Rcpp::DataFrame& mcols);
RcppExport SEXP _ramr_rcpp_prepare_data(SEXP seqnamesSEXP, SEXP seqrunlensSEXP, SEXP startSEXP, SEXP strandSEXP, SEXP mcolsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type seqnames(seqnamesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type seqrunlens(seqrunlensSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type strand(strandSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type mcols(mcolsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_prepare_data(seqnames, seqrunlens, start, strand, mcols));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_extract_out
std::vector<double> rcpp_extract_out(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_extract_out(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_extract_out(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_test_nan
double rcpp_test_nan();
RcppExport SEXP _ramr_rcpp_test_nan() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_test_nan());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_test_med_boost
double rcpp_test_med_boost(std::vector<double> v);
RcppExport SEXP _ramr_rcpp_test_med_boost(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_test_med_boost(v));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_test_iqr_boost
double rcpp_test_iqr_boost(std::vector<double> v);
RcppExport SEXP _ramr_rcpp_test_iqr_boost(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_test_iqr_boost(v));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_test_med
double rcpp_test_med(std::vector<double> v);
RcppExport SEXP _ramr_rcpp_test_med(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_test_med(v));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_test_iqr_type7
std::vector<double> rcpp_test_iqr_type7(std::vector<double> v);
RcppExport SEXP _ramr_rcpp_test_iqr_type7(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_test_iqr_type7(v));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_test_s4v
double rcpp_test_s4v(SEXP x);
RcppExport SEXP _ramr_rcpp_test_s4v(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_test_s4v(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ramr_rcpp_compute_xiqr", (DL_FUNC) &_ramr_rcpp_compute_xiqr, 1},
    {"_ramr_rcpp_filter_threshold_xiqr", (DL_FUNC) &_ramr_rcpp_filter_threshold_xiqr, 2},
    {"_ramr_rcpp_filter_threshold_pval", (DL_FUNC) &_ramr_rcpp_filter_threshold_pval, 2},
    {"_ramr_rcpp_get_iqr", (DL_FUNC) &_ramr_rcpp_get_iqr, 1},
    {"_ramr_rcpp_prepare_data", (DL_FUNC) &_ramr_rcpp_prepare_data, 5},
    {"_ramr_rcpp_extract_out", (DL_FUNC) &_ramr_rcpp_extract_out, 1},
    {"_ramr_rcpp_test_nan", (DL_FUNC) &_ramr_rcpp_test_nan, 0},
    {"_ramr_rcpp_test_med_boost", (DL_FUNC) &_ramr_rcpp_test_med_boost, 1},
    {"_ramr_rcpp_test_iqr_boost", (DL_FUNC) &_ramr_rcpp_test_iqr_boost, 1},
    {"_ramr_rcpp_test_med", (DL_FUNC) &_ramr_rcpp_test_med, 1},
    {"_ramr_rcpp_test_iqr_type7", (DL_FUNC) &_ramr_rcpp_test_iqr_type7, 1},
    {"_ramr_rcpp_test_s4v", (DL_FUNC) &_ramr_rcpp_test_s4v, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ramr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
