// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_compute_logp_beta
int rcpp_compute_logp_beta(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_compute_logp_beta(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_logp_beta(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_compute_logp_beta_binom
int rcpp_compute_logp_beta_binom(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_compute_logp_beta_binom(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_logp_beta_binom(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_compute_xiqr
int rcpp_compute_xiqr(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_compute_xiqr(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_xiqr(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_create_granges_stranded_xiqr
Rcpp::List rcpp_create_granges_stranded_xiqr(Rcpp::List& data, size_t window, size_t min_ncpg, size_t min_width);
RcppExport SEXP _ramr_rcpp_create_granges_stranded_xiqr(SEXP dataSEXP, SEXP windowSEXP, SEXP min_ncpgSEXP, SEXP min_widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< size_t >::type window(windowSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_ncpg(min_ncpgSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_width(min_widthSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_create_granges_stranded_xiqr(data, window, min_ncpg, min_width));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_create_granges_stranded_logp
Rcpp::List rcpp_create_granges_stranded_logp(Rcpp::List& data, size_t window, size_t min_ncpg, size_t min_width);
RcppExport SEXP _ramr_rcpp_create_granges_stranded_logp(SEXP dataSEXP, SEXP windowSEXP, SEXP min_ncpgSEXP, SEXP min_widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< size_t >::type window(windowSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_ncpg(min_ncpgSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_width(min_widthSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_create_granges_stranded_logp(data, window, min_ncpg, min_width));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_create_granges_unstranded_xiqr
Rcpp::List rcpp_create_granges_unstranded_xiqr(Rcpp::List& data, size_t window, size_t min_ncpg, size_t min_width);
RcppExport SEXP _ramr_rcpp_create_granges_unstranded_xiqr(SEXP dataSEXP, SEXP windowSEXP, SEXP min_ncpgSEXP, SEXP min_widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< size_t >::type window(windowSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_ncpg(min_ncpgSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_width(min_widthSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_create_granges_unstranded_xiqr(data, window, min_ncpg, min_width));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_create_granges_unstranded_logp
Rcpp::List rcpp_create_granges_unstranded_logp(Rcpp::List& data, size_t window, size_t min_ncpg, size_t min_width);
RcppExport SEXP _ramr_rcpp_create_granges_unstranded_logp(SEXP dataSEXP, SEXP windowSEXP, SEXP min_ncpgSEXP, SEXP min_widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< size_t >::type window(windowSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_ncpg(min_ncpgSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_width(min_widthSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_create_granges_unstranded_logp(data, window, min_ncpg, min_width));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_filter_threshold_xiqr
int rcpp_filter_threshold_xiqr(Rcpp::List& data, double thr);
RcppExport SEXP _ramr_rcpp_filter_threshold_xiqr(SEXP dataSEXP, SEXP thrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_filter_threshold_xiqr(data, thr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_filter_threshold_logp
int rcpp_filter_threshold_logp(Rcpp::List& data, double thr);
RcppExport SEXP _ramr_rcpp_filter_threshold_logp(SEXP dataSEXP, SEXP thrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_filter_threshold_logp(data, thr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fit_beta_mom
int rcpp_fit_beta_mom(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_fit_beta_mom(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fit_beta_mom(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fit_beta_amle
int rcpp_fit_beta_amle(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_fit_beta_amle(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fit_beta_amle(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fit_beta_nmle
int rcpp_fit_beta_nmle(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_fit_beta_nmle(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fit_beta_nmle(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fit_binom
int rcpp_fit_binom(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_fit_binom(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fit_binom(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_generate_random_values
Rcpp::NumericVector rcpp_generate_random_values(Rcpp::List& data, const size_t ncol);
RcppExport SEXP _ramr_rcpp_generate_random_values(SEXP dataSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const size_t >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_generate_random_values(data, ncol));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_iqr
int rcpp_get_iqr(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_get_iqr(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_iqr(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_meanvar_ari_equal
int rcpp_get_meanvar_ari_equal(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_get_meanvar_ari_equal(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_meanvar_ari_equal(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_meanvar_ari_invDist
int rcpp_get_meanvar_ari_invDist(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_get_meanvar_ari_invDist(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_meanvar_ari_invDist(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_meanvar_ari_sqrtInvDist
int rcpp_get_meanvar_ari_sqrtInvDist(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_get_meanvar_ari_sqrtInvDist(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_meanvar_ari_sqrtInvDist(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_meanvar_ari_logInvDist
int rcpp_get_meanvar_ari_logInvDist(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_get_meanvar_ari_logInvDist(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_meanvar_ari_logInvDist(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_meanvar_geo_equal
int rcpp_get_meanvar_geo_equal(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_get_meanvar_geo_equal(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_meanvar_geo_equal(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_meanvar_geo_invDist
int rcpp_get_meanvar_geo_invDist(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_get_meanvar_geo_invDist(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_meanvar_geo_invDist(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_meanvar_geo_sqrtInvDist
int rcpp_get_meanvar_geo_sqrtInvDist(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_get_meanvar_geo_sqrtInvDist(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_meanvar_geo_sqrtInvDist(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_meanvar_geo_logInvDist
int rcpp_get_meanvar_geo_logInvDist(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_get_meanvar_geo_logInvDist(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_meanvar_geo_logInvDist(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_extract_out
Rcpp::NumericVector rcpp_extract_out(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_extract_out(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_extract_out(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_extract_coef
Rcpp::NumericVector rcpp_extract_coef(Rcpp::List& data);
RcppExport SEXP _ramr_rcpp_extract_coef(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_extract_coef(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_prepare_data_identity
Rcpp::List rcpp_prepare_data_identity(Rcpp::IntegerVector& seqnames, Rcpp::IntegerVector& seqrunlens, Rcpp::IntegerVector& start, Rcpp::IntegerVector& strand, Rcpp::DataFrame& mcols, Rcpp::DataFrame& coverage, double exclude_lower, double exclude_upper, Rcpp::IntegerVector& chunks);
RcppExport SEXP _ramr_rcpp_prepare_data_identity(SEXP seqnamesSEXP, SEXP seqrunlensSEXP, SEXP startSEXP, SEXP strandSEXP, SEXP mcolsSEXP, SEXP coverageSEXP, SEXP exclude_lowerSEXP, SEXP exclude_upperSEXP, SEXP chunksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type seqnames(seqnamesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type seqrunlens(seqrunlensSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type strand(strandSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type mcols(mcolsSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type coverage(coverageSEXP);
    Rcpp::traits::input_parameter< double >::type exclude_lower(exclude_lowerSEXP);
    Rcpp::traits::input_parameter< double >::type exclude_upper(exclude_upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type chunks(chunksSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_prepare_data_identity(seqnames, seqrunlens, start, strand, mcols, coverage, exclude_lower, exclude_upper, chunks));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_prepare_data_linear
Rcpp::List rcpp_prepare_data_linear(Rcpp::IntegerVector& seqnames, Rcpp::IntegerVector& seqrunlens, Rcpp::IntegerVector& start, Rcpp::IntegerVector& strand, Rcpp::DataFrame& mcols, Rcpp::DataFrame& coverage, double exclude_lower, double exclude_upper, Rcpp::IntegerVector& chunks);
RcppExport SEXP _ramr_rcpp_prepare_data_linear(SEXP seqnamesSEXP, SEXP seqrunlensSEXP, SEXP startSEXP, SEXP strandSEXP, SEXP mcolsSEXP, SEXP coverageSEXP, SEXP exclude_lowerSEXP, SEXP exclude_upperSEXP, SEXP chunksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type seqnames(seqnamesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type seqrunlens(seqrunlensSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type strand(strandSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type mcols(mcolsSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type coverage(coverageSEXP);
    Rcpp::traits::input_parameter< double >::type exclude_lower(exclude_lowerSEXP);
    Rcpp::traits::input_parameter< double >::type exclude_upper(exclude_upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type chunks(chunksSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_prepare_data_linear(seqnames, seqrunlens, start, strand, mcols, coverage, exclude_lower, exclude_upper, chunks));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_test_omp
int rcpp_test_omp();
RcppExport SEXP _ramr_rcpp_test_omp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_test_omp());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ramr_rcpp_compute_logp_beta", (DL_FUNC) &_ramr_rcpp_compute_logp_beta, 1},
    {"_ramr_rcpp_compute_logp_beta_binom", (DL_FUNC) &_ramr_rcpp_compute_logp_beta_binom, 1},
    {"_ramr_rcpp_compute_xiqr", (DL_FUNC) &_ramr_rcpp_compute_xiqr, 1},
    {"_ramr_rcpp_create_granges_stranded_xiqr", (DL_FUNC) &_ramr_rcpp_create_granges_stranded_xiqr, 4},
    {"_ramr_rcpp_create_granges_stranded_logp", (DL_FUNC) &_ramr_rcpp_create_granges_stranded_logp, 4},
    {"_ramr_rcpp_create_granges_unstranded_xiqr", (DL_FUNC) &_ramr_rcpp_create_granges_unstranded_xiqr, 4},
    {"_ramr_rcpp_create_granges_unstranded_logp", (DL_FUNC) &_ramr_rcpp_create_granges_unstranded_logp, 4},
    {"_ramr_rcpp_filter_threshold_xiqr", (DL_FUNC) &_ramr_rcpp_filter_threshold_xiqr, 2},
    {"_ramr_rcpp_filter_threshold_logp", (DL_FUNC) &_ramr_rcpp_filter_threshold_logp, 2},
    {"_ramr_rcpp_fit_beta_mom", (DL_FUNC) &_ramr_rcpp_fit_beta_mom, 1},
    {"_ramr_rcpp_fit_beta_amle", (DL_FUNC) &_ramr_rcpp_fit_beta_amle, 1},
    {"_ramr_rcpp_fit_beta_nmle", (DL_FUNC) &_ramr_rcpp_fit_beta_nmle, 1},
    {"_ramr_rcpp_fit_binom", (DL_FUNC) &_ramr_rcpp_fit_binom, 1},
    {"_ramr_rcpp_generate_random_values", (DL_FUNC) &_ramr_rcpp_generate_random_values, 2},
    {"_ramr_rcpp_get_iqr", (DL_FUNC) &_ramr_rcpp_get_iqr, 1},
    {"_ramr_rcpp_get_meanvar_ari_equal", (DL_FUNC) &_ramr_rcpp_get_meanvar_ari_equal, 1},
    {"_ramr_rcpp_get_meanvar_ari_invDist", (DL_FUNC) &_ramr_rcpp_get_meanvar_ari_invDist, 1},
    {"_ramr_rcpp_get_meanvar_ari_sqrtInvDist", (DL_FUNC) &_ramr_rcpp_get_meanvar_ari_sqrtInvDist, 1},
    {"_ramr_rcpp_get_meanvar_ari_logInvDist", (DL_FUNC) &_ramr_rcpp_get_meanvar_ari_logInvDist, 1},
    {"_ramr_rcpp_get_meanvar_geo_equal", (DL_FUNC) &_ramr_rcpp_get_meanvar_geo_equal, 1},
    {"_ramr_rcpp_get_meanvar_geo_invDist", (DL_FUNC) &_ramr_rcpp_get_meanvar_geo_invDist, 1},
    {"_ramr_rcpp_get_meanvar_geo_sqrtInvDist", (DL_FUNC) &_ramr_rcpp_get_meanvar_geo_sqrtInvDist, 1},
    {"_ramr_rcpp_get_meanvar_geo_logInvDist", (DL_FUNC) &_ramr_rcpp_get_meanvar_geo_logInvDist, 1},
    {"_ramr_rcpp_extract_out", (DL_FUNC) &_ramr_rcpp_extract_out, 1},
    {"_ramr_rcpp_extract_coef", (DL_FUNC) &_ramr_rcpp_extract_coef, 1},
    {"_ramr_rcpp_prepare_data_identity", (DL_FUNC) &_ramr_rcpp_prepare_data_identity, 9},
    {"_ramr_rcpp_prepare_data_linear", (DL_FUNC) &_ramr_rcpp_prepare_data_linear, 9},
    {"_ramr_rcpp_test_omp", (DL_FUNC) &_ramr_rcpp_test_omp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ramr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
