// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_test
double rcpp_test();
RcppExport SEXP _ramr_rcpp_test() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_test());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_prepare_data
Rcpp::List rcpp_prepare_data(Rcpp::IntegerVector& seqnames, Rcpp::IntegerVector& seqrunlens, Rcpp::IntegerVector& start, Rcpp::IntegerVector& strand, Rcpp::DataFrame& mcols);
RcppExport SEXP _ramr_rcpp_prepare_data(SEXP seqnamesSEXP, SEXP seqrunlensSEXP, SEXP startSEXP, SEXP strandSEXP, SEXP mcolsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type seqnames(seqnamesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type seqrunlens(seqrunlensSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type strand(strandSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type mcols(mcolsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_prepare_data(seqnames, seqrunlens, start, strand, mcols));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ramr_rcpp_test", (DL_FUNC) &_ramr_rcpp_test, 0},
    {"_ramr_rcpp_prepare_data", (DL_FUNC) &_ramr_rcpp_prepare_data, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ramr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
