# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_compute_iqr <- function(data) {
    .Call(`_ramr_rcpp_compute_iqr`, data)
}

rcpp_prepare_data <- function(seqnames, seqrunlens, start, strand, mcols) {
    .Call(`_ramr_rcpp_prepare_data`, seqnames, seqrunlens, start, strand, mcols)
}

rcpp_test_nan <- function() {
    .Call(`_ramr_rcpp_test_nan`)
}

rcpp_test_med_boost <- function(v) {
    .Call(`_ramr_rcpp_test_med_boost`, v)
}

rcpp_test_iqr_boost <- function(v) {
    .Call(`_ramr_rcpp_test_iqr_boost`, v)
}

rcpp_test_med <- function(v) {
    .Call(`_ramr_rcpp_test_med`, v)
}

rcpp_test_iqr <- function(v) {
    .Call(`_ramr_rcpp_test_iqr`, v)
}

rcpp_test_s4v <- function(x) {
    .Call(`_ramr_rcpp_test_s4v`, x)
}

