# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_test <- function() {
    .Call(`_ramr_rcpp_test`)
}

rcpp_prepare_data <- function(seqnames, seqrunlens, start, strand, mcols) {
    .Call(`_ramr_rcpp_prepare_data`, seqnames, seqrunlens, start, strand, mcols)
}

